# Generated by Django 4.2.10 on 2025-11-28 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('forecast_date', models.DateField()),
                ('predicted_cases', models.IntegerField()),
                ('confidence_interval', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='ForecastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('algorithm', models.CharField(max_length=100)),
                ('model_file', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('TRAINING', 'Training'), ('TRAINED', 'Trained'), ('FAILED', 'Failed'), ('ARCHIVED', 'Archived')], default='TRAINING', max_length=20)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='datasets.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
