# Generated by Django 4.2.10 on 2025-11-29 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0003_pharmacysales_labtest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forecasting', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='actual_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forecast',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forecastmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forecastmodel',
            name='disease',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
        migrations.AddField(
            model_name='forecastmodel',
            name='trained_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecasts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='predicted_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastmodel',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='datasets.dataset'),
        ),
        migrations.AlterField(
            model_name='forecastmodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('TRAINING', 'Training'), ('TRAINED', 'Trained'), ('FAILED', 'Failed'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='forecastmodel',
            name='trained_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trained_models', to=settings.AUTH_USER_MODEL),
        ),
    ]
