# Generated by Django 4.2.26 on 2025-11-30 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forecasting', '0003_forecast_actual_cases_forecast_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=100)),
                ('training_start_date', models.DateField()),
                ('training_end_date', models.DateField()),
                ('forecast_start_date', models.DateField()),
                ('forecast_end_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('TRAINING', 'Training'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('mae_score', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='forecast',
            index=models.Index(fields=['disease', 'forecast_date'], name='forecasting_disease_816a30_idx'),
        ),
        migrations.AddIndex(
            model_name='forecast',
            index=models.Index(fields=['disease', 'region', 'forecast_date'], name='forecasting_disease_5d699d_idx'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to='forecasting.forecastmodel'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='trained_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forecast',
            name='training_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecasts', to='forecasting.trainingsession'),
        ),
    ]
